// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_messages.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countMessagesBySession = `-- name: CountMessagesBySession :one
SELECT COUNT(*) FROM chat_messages
WHERE chat_session_id = $1
`

func (q *Queries) CountMessagesBySession(ctx context.Context, chatSessionID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countMessagesBySession, chatSessionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteMessagesBySession = `-- name: DeleteMessagesBySession :exec
DELETE FROM chat_messages WHERE chat_session_id = $1
`

func (q *Queries) DeleteMessagesBySession(ctx context.Context, chatSessionID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMessagesBySession, chatSessionID)
	return err
}

const getChatMessageByID = `-- name: GetChatMessageByID :one
SELECT id, chat_session_id, seq, role, content, status, elapsed_ms, failure_reason, created_at
FROM chat_messages
WHERE id = $1
`

func (q *Queries) GetChatMessageByID(ctx context.Context, id pgtype.UUID) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, getChatMessageByID, id)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatSessionID,
		&i.Seq,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ElapsedMs,
		&i.FailureReason,
		&i.CreatedAt,
	)
	return i, err
}

const getChatMessagesBySession = `-- name: GetChatMessagesBySession :many
SELECT id, chat_session_id, seq, role, content, status, elapsed_ms, failure_reason, created_at
FROM chat_messages
WHERE chat_session_id = $1
ORDER BY seq ASC
`

func (q *Queries) GetChatMessagesBySession(ctx context.Context, chatSessionID pgtype.UUID) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getChatMessagesBySession, chatSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatSessionID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.Status,
			&i.ElapsedMs,
			&i.FailureReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextSeqForSession = `-- name: GetNextSeqForSession :one
SELECT COALESCE(MAX(seq), 0) + 1 AS next_seq
FROM chat_messages
WHERE chat_session_id = $1
`

func (q *Queries) GetNextSeqForSession(ctx context.Context, chatSessionID pgtype.UUID) (int32, error) {
	row := q.db.QueryRow(ctx, getNextSeqForSession, chatSessionID)
	var next_seq int32
	err := row.Scan(&next_seq)
	return next_seq, err
}

const getRecentMessagesBySession = `-- name: GetRecentMessagesBySession :many
SELECT id, chat_session_id, seq, role, content, status, elapsed_ms, failure_reason, created_at
FROM chat_messages
WHERE chat_session_id = $1
ORDER BY seq DESC
LIMIT $2
`

type GetRecentMessagesBySessionParams struct {
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
	Limit         int32       `json:"limit"`
}

func (q *Queries) GetRecentMessagesBySession(ctx context.Context, arg GetRecentMessagesBySessionParams) ([]ChatMessage, error) {
	rows, err := q.db.Query(ctx, getRecentMessagesBySession, arg.ChatSessionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatMessage{}
	for rows.Next() {
		var i ChatMessage
		if err := rows.Scan(
			&i.ID,
			&i.ChatSessionID,
			&i.Seq,
			&i.Role,
			&i.Content,
			&i.Status,
			&i.ElapsedMs,
			&i.FailureReason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertChatMessage = `-- name: InsertChatMessage :one
INSERT INTO chat_messages (chat_session_id, seq, role, content, status, elapsed_ms, failure_reason)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, chat_session_id, seq, role, content, status, elapsed_ms, failure_reason, created_at
`

type InsertChatMessageParams struct {
	ChatSessionID pgtype.UUID `json:"chat_session_id"`
	Seq           int32       `json:"seq"`
	Role          string      `json:"role"`
	Content       string      `json:"content"`
	Status        string      `json:"status"`
	ElapsedMs     pgtype.Int4 `json:"elapsed_ms"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (ChatMessage, error) {
	row := q.db.QueryRow(ctx, insertChatMessage,
		arg.ChatSessionID,
		arg.Seq,
		arg.Role,
		arg.Content,
		arg.Status,
		arg.ElapsedMs,
		arg.FailureReason,
	)
	var i ChatMessage
	err := row.Scan(
		&i.ID,
		&i.ChatSessionID,
		&i.Seq,
		&i.Role,
		&i.Content,
		&i.Status,
		&i.ElapsedMs,
		&i.FailureReason,
		&i.CreatedAt,
	)
	return i, err
}

const updateMessageStatus = `-- name: UpdateMessageStatus :exec
UPDATE chat_messages
SET status = $2, elapsed_ms = $3, failure_reason = $4
WHERE id = $1
`

type UpdateMessageStatusParams struct {
	ID            pgtype.UUID `json:"id"`
	Status        string      `json:"status"`
	ElapsedMs     pgtype.Int4 `json:"elapsed_ms"`
	FailureReason pgtype.Text `json:"failure_reason"`
}

func (q *Queries) UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error {
	_, err := q.db.Exec(ctx, updateMessageStatus,
		arg.ID,
		arg.Status,
		arg.ElapsedMs,
		arg.FailureReason,
	)
	return err
}
