// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: chat_sessions.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveChatSession = `-- name: ArchiveChatSession :exec
UPDATE chat_sessions
SET status = 'archived', updated_at = now()
WHERE id = $1
`

func (q *Queries) ArchiveChatSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveChatSession, id)
	return err
}

const countChatSessionsByUser = `-- name: CountChatSessionsByUser :one
SELECT COUNT(*) FROM chat_sessions
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) CountChatSessionsByUser(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countChatSessionsByUser, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createChatSession = `-- name: CreateChatSession :one
INSERT INTO chat_sessions (user_id, title, status)
VALUES ($1, 'New Chat', 'active')
RETURNING id, user_id, runtime_id, title, status, created_at, updated_at
`

func (q *Queries) CreateChatSession(ctx context.Context, userID pgtype.UUID) (ChatSession, error) {
	row := q.db.QueryRow(ctx, createChatSession, userID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RuntimeID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteChatSession = `-- name: DeleteChatSession :exec
DELETE FROM chat_sessions WHERE id = $1
`

func (q *Queries) DeleteChatSession(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteChatSession, id)
	return err
}

const getChatSession = `-- name: GetChatSession :one
SELECT id, user_id, runtime_id, title, status, created_at, updated_at
FROM chat_sessions
WHERE id = $1
`

func (q *Queries) GetChatSession(ctx context.Context, id pgtype.UUID) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSession, id)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RuntimeID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getChatSessionByIDAndUser = `-- name: GetChatSessionByIDAndUser :one
SELECT id, user_id, runtime_id, title, status, created_at, updated_at
FROM chat_sessions
WHERE id = $1 AND user_id = $2
`

type GetChatSessionByIDAndUserParams struct {
	ID     pgtype.UUID `json:"id"`
	UserID pgtype.UUID `json:"user_id"`
}

func (q *Queries) GetChatSessionByIDAndUser(ctx context.Context, arg GetChatSessionByIDAndUserParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, getChatSessionByIDAndUser, arg.ID, arg.UserID)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RuntimeID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listChatSessionsByUser = `-- name: ListChatSessionsByUser :many
SELECT cs.id, cs.user_id, cs.runtime_id, cs.title, cs.status, cs.created_at, cs.updated_at
FROM chat_sessions cs
WHERE cs.user_id = $1 AND cs.status = 'active'
ORDER BY cs.updated_at DESC
LIMIT $2 OFFSET $3
`

type ListChatSessionsByUserParams struct {
	UserID pgtype.UUID `json:"user_id"`
	Limit  int32       `json:"limit"`
	Offset int32       `json:"offset"`
}

func (q *Queries) ListChatSessionsByUser(ctx context.Context, arg ListChatSessionsByUserParams) ([]ChatSession, error) {
	rows, err := q.db.Query(ctx, listChatSessionsByUser, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ChatSession{}
	for rows.Next() {
		var i ChatSession
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.RuntimeID,
			&i.Title,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChatSessionRuntime = `-- name: UpdateChatSessionRuntime :exec
UPDATE chat_sessions
SET runtime_id = $2, updated_at = now()
WHERE id = $1
`

type UpdateChatSessionRuntimeParams struct {
	ID        pgtype.UUID `json:"id"`
	RuntimeID pgtype.UUID `json:"runtime_id"`
}

func (q *Queries) UpdateChatSessionRuntime(ctx context.Context, arg UpdateChatSessionRuntimeParams) error {
	_, err := q.db.Exec(ctx, updateChatSessionRuntime, arg.ID, arg.RuntimeID)
	return err
}

const updateChatSessionTitle = `-- name: UpdateChatSessionTitle :one
UPDATE chat_sessions
SET title = $2, updated_at = now()
WHERE id = $1
RETURNING id, user_id, runtime_id, title, status, created_at, updated_at
`

type UpdateChatSessionTitleParams struct {
	ID    pgtype.UUID `json:"id"`
	Title string      `json:"title"`
}

func (q *Queries) UpdateChatSessionTitle(ctx context.Context, arg UpdateChatSessionTitleParams) (ChatSession, error) {
	row := q.db.QueryRow(ctx, updateChatSessionTitle, arg.ID, arg.Title)
	var i ChatSession
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.RuntimeID,
		&i.Title,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
