// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daemons.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const deleteDaemon = `-- name: DeleteDaemon :exec
DELETE FROM daemons WHERE id = $1
`

func (q *Queries) DeleteDaemon(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDaemon, id)
	return err
}

const getDaemonByDaemonID = `-- name: GetDaemonByDaemonID :one
SELECT id, user_id, daemon_id, status, last_seen_at, created_at, updated_at
FROM daemons
WHERE daemon_id = $1
`

func (q *Queries) GetDaemonByDaemonID(ctx context.Context, daemonID string) (Daemon, error) {
	row := q.db.QueryRow(ctx, getDaemonByDaemonID, daemonID)
	var i Daemon
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DaemonID,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDaemonByID = `-- name: GetDaemonByID :one
SELECT id, user_id, daemon_id, status, last_seen_at, created_at, updated_at
FROM daemons
WHERE id = $1
`

func (q *Queries) GetDaemonByID(ctx context.Context, id pgtype.UUID) (Daemon, error) {
	row := q.db.QueryRow(ctx, getDaemonByID, id)
	var i Daemon
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DaemonID,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDaemonsByUserID = `-- name: GetDaemonsByUserID :many
SELECT id, user_id, daemon_id, status, last_seen_at, created_at, updated_at
FROM daemons
WHERE user_id = $1
ORDER BY last_seen_at DESC
`

func (q *Queries) GetDaemonsByUserID(ctx context.Context, userID pgtype.UUID) ([]Daemon, error) {
	rows, err := q.db.Query(ctx, getDaemonsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Daemon{}
	for rows.Next() {
		var i Daemon
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DaemonID,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleDaemons = `-- name: GetStaleDaemons :many
SELECT id, user_id, daemon_id, status, last_seen_at, created_at, updated_at
FROM daemons
WHERE status = 'online'
  AND last_seen_at < $1
`

func (q *Queries) GetStaleDaemons(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]Daemon, error) {
	rows, err := q.db.Query(ctx, getStaleDaemons, lastSeenAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Daemon{}
	for rows.Next() {
		var i Daemon
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.DaemonID,
			&i.Status,
			&i.LastSeenAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markDaemonOffline = `-- name: MarkDaemonOffline :exec
UPDATE daemons
SET status = 'offline', updated_at = now()
WHERE daemon_id = $1
`

func (q *Queries) MarkDaemonOffline(ctx context.Context, daemonID string) error {
	_, err := q.db.Exec(ctx, markDaemonOffline, daemonID)
	return err
}

const markDaemonOfflineByID = `-- name: MarkDaemonOfflineByID :exec
UPDATE daemons
SET status = 'offline', updated_at = now()
WHERE id = $1
`

func (q *Queries) MarkDaemonOfflineByID(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markDaemonOfflineByID, id)
	return err
}

const updateDaemonHeartbeat = `-- name: UpdateDaemonHeartbeat :exec
UPDATE daemons
SET last_seen_at = now(), updated_at = now()
WHERE daemon_id = $1
`

func (q *Queries) UpdateDaemonHeartbeat(ctx context.Context, daemonID string) error {
	_, err := q.db.Exec(ctx, updateDaemonHeartbeat, daemonID)
	return err
}

const upsertDaemon = `-- name: UpsertDaemon :one
INSERT INTO daemons (user_id, daemon_id, status, last_seen_at)
VALUES ($1, $2, 'online', now())
ON CONFLICT (daemon_id) DO UPDATE
SET user_id = EXCLUDED.user_id,
    status = 'online',
    last_seen_at = now(),
    updated_at = now()
RETURNING id, user_id, daemon_id, status, last_seen_at, created_at, updated_at
`

type UpsertDaemonParams struct {
	UserID   pgtype.UUID `json:"user_id"`
	DaemonID string      `json:"daemon_id"`
}

func (q *Queries) UpsertDaemon(ctx context.Context, arg UpsertDaemonParams) (Daemon, error) {
	row := q.db.QueryRow(ctx, upsertDaemon, arg.UserID, arg.DaemonID)
	var i Daemon
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.DaemonID,
		&i.Status,
		&i.LastSeenAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
