// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daemon_tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDaemonToken = `-- name: CreateDaemonToken :one
INSERT INTO daemon_tokens (user_id, name, token_hash, expires_at)
VALUES ($1, $2, $3, $4)
RETURNING id, user_id, name, token_hash, expires_at, created_at, last_used_at
`

type CreateDaemonTokenParams struct {
	UserID    pgtype.UUID        `json:"user_id"`
	Name      string             `json:"name"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

func (q *Queries) CreateDaemonToken(ctx context.Context, arg CreateDaemonTokenParams) (DaemonToken, error) {
	row := q.db.QueryRow(ctx, createDaemonToken, arg.UserID, arg.Name, arg.TokenHash, arg.ExpiresAt)
	var i DaemonToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const getDaemonTokenByHash = `-- name: GetDaemonTokenByHash :one
SELECT id, user_id, name, token_hash, expires_at, created_at, last_used_at
FROM daemon_tokens
WHERE token_hash = $1 AND expires_at > now()
`

func (q *Queries) GetDaemonTokenByHash(ctx context.Context, tokenHash string) (DaemonToken, error) {
	row := q.db.QueryRow(ctx, getDaemonTokenByHash, tokenHash)
	var i DaemonToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.CreatedAt,
		&i.LastUsedAt,
	)
	return i, err
}

const updateDaemonTokenLastUsed = `-- name: UpdateDaemonTokenLastUsed :exec
UPDATE daemon_tokens
SET last_used_at = now()
WHERE id = $1
`

func (q *Queries) UpdateDaemonTokenLastUsed(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, updateDaemonTokenLastUsed, id)
	return err
}

const deleteDaemonTokenByHash = `-- name: DeleteDaemonTokenByHash :exec
DELETE FROM daemon_tokens
WHERE token_hash = $1
`

func (q *Queries) DeleteDaemonTokenByHash(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, deleteDaemonTokenByHash, tokenHash)
	return err
}

const deleteDaemonTokensByUserID = `-- name: DeleteDaemonTokensByUserID :exec
DELETE FROM daemon_tokens
WHERE user_id = $1
`

func (q *Queries) DeleteDaemonTokensByUserID(ctx context.Context, userID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDaemonTokensByUserID, userID)
	return err
}
