// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: message_buffer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addToMessageBuffer = `-- name: AddToMessageBuffer :one
INSERT INTO message_buffer (user_id, payload, expires_at)
VALUES ($1, $2, now() + INTERVAL '5 minutes')
RETURNING id, user_id, payload, created_at, expires_at
`

type AddToMessageBufferParams struct {
	UserID  pgtype.UUID `json:"user_id"`
	Payload []byte      `json:"payload"`
}

func (q *Queries) AddToMessageBuffer(ctx context.Context, arg AddToMessageBufferParams) (MessageBuffer, error) {
	row := q.db.QueryRow(ctx, addToMessageBuffer, arg.UserID, arg.Payload)
	var i MessageBuffer
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Payload,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const cleanupExpiredBufferMessages = `-- name: CleanupExpiredBufferMessages :exec
DELETE FROM message_buffer
WHERE expires_at <= now()
`

func (q *Queries) CleanupExpiredBufferMessages(ctx context.Context) error {
	_, err := q.db.Exec(ctx, cleanupExpiredBufferMessages)
	return err
}

const countBufferedMessages = `-- name: CountBufferedMessages :one
SELECT COUNT(*) FROM message_buffer
WHERE user_id = $1 AND expires_at > now()
`

func (q *Queries) CountBufferedMessages(ctx context.Context, userID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBufferedMessages, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBufferedMessages = `-- name: DeleteBufferedMessages :exec
DELETE FROM message_buffer
WHERE user_id = $1
  AND id = ANY($2::uuid[])
`

type DeleteBufferedMessagesParams struct {
	UserID  pgtype.UUID   `json:"user_id"`
	Column2 []pgtype.UUID `json:"column_2"`
}

func (q *Queries) DeleteBufferedMessages(ctx context.Context, arg DeleteBufferedMessagesParams) error {
	_, err := q.db.Exec(ctx, deleteBufferedMessages, arg.UserID, arg.Column2)
	return err
}

const drainMessageBuffer = `-- name: DrainMessageBuffer :many
SELECT id, user_id, payload, created_at, expires_at
FROM message_buffer
WHERE user_id = $1
  AND expires_at > now()
ORDER BY created_at ASC
LIMIT 100
`

func (q *Queries) DrainMessageBuffer(ctx context.Context, userID pgtype.UUID) ([]MessageBuffer, error) {
	rows, err := q.db.Query(ctx, drainMessageBuffer, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MessageBuffer{}
	for rows.Next() {
		var i MessageBuffer
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Payload,
			&i.CreatedAt,
			&i.ExpiresAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
