// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type DaemonToken struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     string             `json:"user_id"`
	Name       string             `json:"name"`
	TokenHash  string             `json:"token_hash"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
}

type ChatMessage struct {
	ID            pgtype.UUID        `json:"id"`
	ChatSessionID pgtype.UUID        `json:"chat_session_id"`
	Seq           int32              `json:"seq"`
	Role          string             `json:"role"`
	Content       string             `json:"content"`
	Status        string             `json:"status"`
	ElapsedMs     pgtype.Int4        `json:"elapsed_ms"`
	FailureReason pgtype.Text        `json:"failure_reason"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
}

type ChatSession struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	RuntimeID pgtype.UUID        `json:"runtime_id"`
	Title     string             `json:"title"`
	Status    string             `json:"status"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type Daemon struct {
	ID         pgtype.UUID        `json:"id"`
	UserID     pgtype.UUID        `json:"user_id"`
	DaemonID   string             `json:"daemon_id"`
	Status     string             `json:"status"`
	LastSeenAt pgtype.Timestamptz `json:"last_seen_at"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type MessageBuffer struct {
	ID        pgtype.UUID        `json:"id"`
	UserID    pgtype.UUID        `json:"user_id"`
	Payload   []byte             `json:"payload"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	ExpiresAt pgtype.Timestamptz `json:"expires_at"`
}

type Runtime struct {
	ID         pgtype.UUID        `json:"id"`
	DaemonID   pgtype.UUID        `json:"daemon_id"`
	AgentType  string             `json:"agent_type"`
	BinaryPath string             `json:"binary_path"`
	Version    string             `json:"version"`
	Status     string             `json:"status"`
	CreatedAt  pgtype.Timestamptz `json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `json:"updated_at"`
}

type User struct {
	ID           pgtype.UUID        `json:"id"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	DisplayName  string             `json:"display_name"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}
