// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddToMessageBuffer(ctx context.Context, arg AddToMessageBufferParams) (MessageBuffer, error)
	ArchiveChatSession(ctx context.Context, id pgtype.UUID) error
	CreateDaemonToken(ctx context.Context, arg CreateDaemonTokenParams) (DaemonToken, error)
	DeleteDaemonTokenByHash(ctx context.Context, tokenHash string) error
	DeleteDaemonTokensByUserID(ctx context.Context, userID pgtype.UUID) error
	GetDaemonTokenByHash(ctx context.Context, tokenHash string) (DaemonToken, error)
	UpdateDaemonTokenLastUsed(ctx context.Context, id pgtype.UUID) error
	CleanupExpiredBufferMessages(ctx context.Context) error
	CountBufferedMessages(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountChatSessionsByUser(ctx context.Context, userID pgtype.UUID) (int64, error)
	CountMessagesBySession(ctx context.Context, chatSessionID pgtype.UUID) (int64, error)
	CreateChatSession(ctx context.Context, userID pgtype.UUID) (ChatSession, error)
	CreateRuntime(ctx context.Context, arg CreateRuntimeParams) (Runtime, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteBufferedMessages(ctx context.Context, arg DeleteBufferedMessagesParams) error
	DeleteChatSession(ctx context.Context, id pgtype.UUID) error
	DeleteDaemon(ctx context.Context, id pgtype.UUID) error
	DeleteMessagesBySession(ctx context.Context, chatSessionID pgtype.UUID) error
	DeleteRuntimesByDaemonID(ctx context.Context, daemonID pgtype.UUID) error
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	DrainMessageBuffer(ctx context.Context, userID pgtype.UUID) ([]MessageBuffer, error)
	GetAvailableRuntimesByUserID(ctx context.Context, userID pgtype.UUID) ([]Runtime, error)
	GetChatMessageByID(ctx context.Context, id pgtype.UUID) (ChatMessage, error)
	GetChatMessagesBySession(ctx context.Context, chatSessionID pgtype.UUID) ([]ChatMessage, error)
	GetChatSession(ctx context.Context, id pgtype.UUID) (ChatSession, error)
	GetChatSessionByIDAndUser(ctx context.Context, arg GetChatSessionByIDAndUserParams) (ChatSession, error)
	GetDaemonByDaemonID(ctx context.Context, daemonID string) (Daemon, error)
	GetDaemonByID(ctx context.Context, id pgtype.UUID) (Daemon, error)
	GetDaemonsByUserID(ctx context.Context, userID pgtype.UUID) ([]Daemon, error)
	GetNextSeqForSession(ctx context.Context, chatSessionID pgtype.UUID) (int32, error)
	GetRecentMessagesBySession(ctx context.Context, arg GetRecentMessagesBySessionParams) ([]ChatMessage, error)
	GetRuntimeByID(ctx context.Context, id pgtype.UUID) (Runtime, error)
	GetRuntimesByDaemonID(ctx context.Context, daemonID pgtype.UUID) ([]Runtime, error)
	GetStaleDaemons(ctx context.Context, lastSeenAt pgtype.Timestamptz) ([]Daemon, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserByID(ctx context.Context, id pgtype.UUID) (User, error)
	InsertChatMessage(ctx context.Context, arg InsertChatMessageParams) (ChatMessage, error)
	ListChatSessionsByUser(ctx context.Context, arg ListChatSessionsByUserParams) ([]ChatSession, error)
	MarkDaemonOffline(ctx context.Context, daemonID string) error
	MarkDaemonOfflineByID(ctx context.Context, id pgtype.UUID) error
	MarkRuntimesOfflineByDaemonID(ctx context.Context, daemonID pgtype.UUID) error
	UpdateChatSessionRuntime(ctx context.Context, arg UpdateChatSessionRuntimeParams) error
	UpdateChatSessionTitle(ctx context.Context, arg UpdateChatSessionTitleParams) (ChatSession, error)
	UpdateDaemonHeartbeat(ctx context.Context, daemonID string) error
	UpdateMessageStatus(ctx context.Context, arg UpdateMessageStatusParams) error
	UpdateRuntimeStatus(ctx context.Context, arg UpdateRuntimeStatusParams) error
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	UpsertDaemon(ctx context.Context, arg UpsertDaemonParams) (Daemon, error)
	UserExists(ctx context.Context, id pgtype.UUID) (bool, error)
}

var _ Querier = (*Queries)(nil)
