// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: runtimes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createRuntime = `-- name: CreateRuntime :one
INSERT INTO runtimes (daemon_id, agent_type, binary_path, version, status)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, daemon_id, agent_type, binary_path, version, status, created_at, updated_at
`

type CreateRuntimeParams struct {
	DaemonID   pgtype.UUID `json:"daemon_id"`
	AgentType  string      `json:"agent_type"`
	BinaryPath string      `json:"binary_path"`
	Version    string      `json:"version"`
	Status     string      `json:"status"`
}

func (q *Queries) CreateRuntime(ctx context.Context, arg CreateRuntimeParams) (Runtime, error) {
	row := q.db.QueryRow(ctx, createRuntime,
		arg.DaemonID,
		arg.AgentType,
		arg.BinaryPath,
		arg.Version,
		arg.Status,
	)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.DaemonID,
		&i.AgentType,
		&i.BinaryPath,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteRuntimesByDaemonID = `-- name: DeleteRuntimesByDaemonID :exec
DELETE FROM runtimes WHERE daemon_id = $1
`

func (q *Queries) DeleteRuntimesByDaemonID(ctx context.Context, daemonID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteRuntimesByDaemonID, daemonID)
	return err
}

const getAvailableRuntimesByUserID = `-- name: GetAvailableRuntimesByUserID :many
SELECT r.id, r.daemon_id, r.agent_type, r.binary_path, r.version, r.status, r.created_at, r.updated_at
FROM runtimes r
JOIN daemons d ON r.daemon_id = d.id
WHERE d.user_id = $1
  AND r.status = 'available'
  AND d.status = 'online'
ORDER BY r.agent_type
`

func (q *Queries) GetAvailableRuntimesByUserID(ctx context.Context, userID pgtype.UUID) ([]Runtime, error) {
	rows, err := q.db.Query(ctx, getAvailableRuntimesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Runtime{}
	for rows.Next() {
		var i Runtime
		if err := rows.Scan(
			&i.ID,
			&i.DaemonID,
			&i.AgentType,
			&i.BinaryPath,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRuntimeByID = `-- name: GetRuntimeByID :one
SELECT id, daemon_id, agent_type, binary_path, version, status, created_at, updated_at
FROM runtimes
WHERE id = $1
`

func (q *Queries) GetRuntimeByID(ctx context.Context, id pgtype.UUID) (Runtime, error) {
	row := q.db.QueryRow(ctx, getRuntimeByID, id)
	var i Runtime
	err := row.Scan(
		&i.ID,
		&i.DaemonID,
		&i.AgentType,
		&i.BinaryPath,
		&i.Version,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getRuntimesByDaemonID = `-- name: GetRuntimesByDaemonID :many
SELECT id, daemon_id, agent_type, binary_path, version, status, created_at, updated_at
FROM runtimes
WHERE daemon_id = $1
ORDER BY agent_type
`

func (q *Queries) GetRuntimesByDaemonID(ctx context.Context, daemonID pgtype.UUID) ([]Runtime, error) {
	rows, err := q.db.Query(ctx, getRuntimesByDaemonID, daemonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Runtime{}
	for rows.Next() {
		var i Runtime
		if err := rows.Scan(
			&i.ID,
			&i.DaemonID,
			&i.AgentType,
			&i.BinaryPath,
			&i.Version,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markRuntimesOfflineByDaemonID = `-- name: MarkRuntimesOfflineByDaemonID :exec
UPDATE runtimes
SET status = 'offline', updated_at = now()
WHERE daemon_id = $1
`

func (q *Queries) MarkRuntimesOfflineByDaemonID(ctx context.Context, daemonID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markRuntimesOfflineByDaemonID, daemonID)
	return err
}

const updateRuntimeStatus = `-- name: UpdateRuntimeStatus :exec
UPDATE runtimes
SET status = $2, updated_at = now()
WHERE id = $1
`

type UpdateRuntimeStatusParams struct {
	ID     pgtype.UUID `json:"id"`
	Status string      `json:"status"`
}

func (q *Queries) UpdateRuntimeStatus(ctx context.Context, arg UpdateRuntimeStatusParams) error {
	_, err := q.db.Exec(ctx, updateRuntimeStatus, arg.ID, arg.Status)
	return err
}
