package handler

import (
	"crypto/rand"
	"crypto/sha256"
	"encoding/hex"
	"strings"
	"testing"
	"unicode/utf8"

	"pgregory.net/rapid"
)

// Feature: daemon-browser-login, Property 4: Daemon Token Format Invariant
// For any daemon token generated by the Token_Endpoint, the token SHALL start with "ab_",
// have a total length of exactly 67 characters, and the 64 characters after the prefix
// SHALL all be valid lowercase hexadecimal digits.
//
// **Validates: Requirements 2.2**

// GenerateDaemonToken replicates the token generation logic from CreateToken handler.
// It generates a daemon token: "ab_" prefix + 32 random bytes as lowercase hex.
func GenerateDaemonToken() (string, error) {
	tokenBytes := make([]byte, 32)
	if _, err := rand.Read(tokenBytes); err != nil {
		return "", err
	}
	return "ab_" + hex.EncodeToString(tokenBytes), nil
}

// isLowercaseHex checks if a string contains only valid lowercase hexadecimal digits.
func isLowercaseHex(s string) bool {
	for _, c := range s {
		if !((c >= '0' && c <= '9') || (c >= 'a' && c <= 'f')) {
			return false
		}
	}
	return true
}

func TestProperty_DaemonTokenFormatInvariant(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		// Generate a daemon token using the same logic as the handler.
		token, err := GenerateDaemonToken()
		if err != nil {
			t.Fatalf("failed to generate daemon token: %v", err)
		}

		// Property: token starts with "ab_"
		if !strings.HasPrefix(token, "ab_") {
			t.Fatalf("token does not start with 'ab_': %q", token)
		}

		// Property: total length is exactly 67 characters
		if utf8.RuneCountInString(token) != 67 {
			t.Fatalf("token length is %d, expected 67: %q", utf8.RuneCountInString(token), token)
		}

		// Property: the 64 characters after the prefix are all valid lowercase hex digits
		hexPart := token[3:]
		if len(hexPart) != 64 {
			t.Fatalf("hex part length is %d, expected 64: %q", len(hexPart), hexPart)
		}
		if !isLowercaseHex(hexPart) {
			t.Fatalf("hex part contains non-lowercase-hex characters: %q", hexPart)
		}
	})
}

// TestProperty_DaemonTokenFormatFromArbitraryBytes tests that for any arbitrary
// 32-byte sequence, the token format invariant holds. This tests the encoding
// logic independently of crypto/rand.
func TestProperty_DaemonTokenFormatFromArbitraryBytes(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		// Generate an arbitrary 32-byte slice.
		rawBytes := make([]byte, 32)
		for i := range rawBytes {
			rawBytes[i] = rapid.Byte().Draw(t, "byte")
		}

		// Construct token the same way the handler does.
		token := "ab_" + hex.EncodeToString(rawBytes)

		// Property: token starts with "ab_"
		if !strings.HasPrefix(token, "ab_") {
			t.Fatalf("token does not start with 'ab_': %q", token)
		}

		// Property: total length is exactly 67 characters
		if len(token) != 67 {
			t.Fatalf("token length is %d, expected 67: %q", len(token), token)
		}

		// Property: the 64 characters after the prefix are all valid lowercase hex digits
		hexPart := token[3:]
		if len(hexPart) != 64 {
			t.Fatalf("hex part length is %d, expected 64: %q", len(hexPart), hexPart)
		}
		if !isLowercaseHex(hexPart) {
			t.Fatalf("hex part contains non-lowercase-hex characters: %q", hexPart)
		}
	})
}

// Feature: daemon-browser-login, Property 5: Token Hash Verification
// For any generated daemon token T, the value stored in token_hash in the database
// SHALL equal hex(SHA-256(T)), and looking up hex(SHA-256(T)) in the daemon_tokens
// table SHALL find the corresponding record.
//
// **Validates: Requirements 2.3, 6.1**

// ComputeTokenHash replicates the hash computation from the CreateToken handler.
func ComputeTokenHash(token string) string {
	hash := sha256.Sum256([]byte(token))
	return hex.EncodeToString(hash[:])
}

func TestProperty_TokenHashVerification(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		// Generate an arbitrary 32-byte slice to construct a token.
		rawBytes := make([]byte, 32)
		for i := range rawBytes {
			rawBytes[i] = rapid.Byte().Draw(t, "byte")
		}

		// Construct token the same way the handler does.
		token := "ab_" + hex.EncodeToString(rawBytes)

		// Compute the hash the same way the handler does.
		hash := sha256.Sum256([]byte(token))
		tokenHash := hex.EncodeToString(hash[:])

		// Property: the hash is a valid 64-character lowercase hex string (SHA-256 output).
		if len(tokenHash) != 64 {
			t.Fatalf("token hash length is %d, expected 64: %q", len(tokenHash), tokenHash)
		}
		if !isLowercaseHex(tokenHash) {
			t.Fatalf("token hash contains non-lowercase-hex characters: %q", tokenHash)
		}

		// Property: computing the hash again from the same token produces the same result.
		// This verifies the deterministic round-trip: token -> hash -> lookup would find the record.
		tokenHashAgain := ComputeTokenHash(token)
		if tokenHash != tokenHashAgain {
			t.Fatalf("hash mismatch: first=%q, second=%q", tokenHash, tokenHashAgain)
		}

		// Property: different tokens produce different hashes (collision resistance).
		// Generate a second distinct token.
		rawBytes2 := make([]byte, 32)
		for i := range rawBytes2 {
			rawBytes2[i] = rapid.Byte().Draw(t, "byte2")
		}
		token2 := "ab_" + hex.EncodeToString(rawBytes2)
		if token != token2 {
			tokenHash2 := ComputeTokenHash(token2)
			if tokenHash == tokenHash2 {
				t.Fatalf("hash collision detected: token1=%q, token2=%q, hash=%q", token, token2, tokenHash)
			}
		}
	})
}

// TestProperty_TokenHashMatchesStoredFormat verifies that the hash stored in the
// database (as computed by the handler) can be used to look up the token.
// This simulates the lookup: given a token T, compute hex(SHA-256(T)) and verify
// it matches what would have been stored during token creation.
func TestProperty_TokenHashMatchesStoredFormat(t *testing.T) {
	rapid.Check(t, func(t *rapid.T) {
		// Generate an arbitrary 32-byte slice.
		rawBytes := make([]byte, 32)
		for i := range rawBytes {
			rawBytes[i] = rapid.Byte().Draw(t, "byte")
		}

		// Simulate token creation (what the handler does).
		token := "ab_" + hex.EncodeToString(rawBytes)
		createHash := sha256.Sum256([]byte(token))
		storedHash := hex.EncodeToString(createHash[:])

		// Simulate token authentication (what the middleware does).
		// Given the same token, compute the hash for lookup.
		authHash := sha256.Sum256([]byte(token))
		lookupHash := hex.EncodeToString(authHash[:])

		// Property: the lookup hash equals the stored hash.
		// This proves that looking up hex(SHA-256(T)) in daemon_tokens will find the record.
		if storedHash != lookupHash {
			t.Fatalf("stored hash %q does not match lookup hash %q for token %q",
				storedHash, lookupHash, token)
		}
	})
}
